#! /bin/sh
### BEGIN INIT INFO
# Provides: MyDashboard
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Infoscreen Dashboard
# Description:
### END INIT INFO
 
case "$1" in
    start)
        echo "My dashboard wird gestartet"
        # Starte Programm
        sudo -u pi /home/pi/work/InfoScreen/bin/start_dashboard
        ;;
    stop)
        echo "My Dashboard"
        # Beende Programm
        killall chromium-browser
        ;;
    *)
        echo "Benutzt: /etc/init.d/MyDashboard {start|stop}"
        exit 1
        ;;
esac
 
exit 0
